name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  deploy:
    name: Build & Deploy Fullstack App
    runs-on: self-hosted

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 21

      - name: Install PM2 Globally
        run: npm install -g pm2

      - name: Install Backend Dependencies
        run: |
          cd Backend
          npm install

      - name: Start Backend with PM2
        run: |
          cd Backend
          pm2 delete backend || true  # Remove existing process if running
          pm2 start npm --name backend -- start
          pm2 save  # Save PM2 state

      - name: Install Frontend Dependencies
        run: |
          cd Frontend
          npm install

      - name: Start Frontend with PM2
        run: |
          cd Frontend
          pm2 delete frontend || true  # Remove existing process if running
          pm2 start npm --name frontend -- start
          pm2 save  # Save PM2 state
