name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  frontend:
    name: Build & Deploy Frontend
    runs-on: self-hosted

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 21

      - name: Install Dependencies
        run: |
          cd Frontend
          npm install


      - name: Build Frontend
        run: |
          cd Frontend
          npm run build

      - name: Deploy Frontend (Optional)
        run: echo "Deploy step for frontend"

  backend:
    name: Build & Deploy Backend
    runs-on: self-hosted
    needs: frontend

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 21

      - name: Install Dependencies
        run: |
          cd Backend
          npm install

      - name: Start Backend
        run: |
          cd Backend
          npm start

      - name: Deploy Backend (Optional)
        run: echo "Deploy step for backend"
